apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: spring-app
  ports:
    - port: 8089         # <-- IMPORTANT
      targetPort: 8089   # <-- IMPORTANT
      nodePort: 30080
  type: NodePort

